# Generated by Django 5.1.6 on 2025-02-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='big_image',
        ),
    ]
