# Generated by Django 5.1.6 on 2025-08-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcharacteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
