# Generated by Django 5.1.6 on 2025-08-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristics',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
