# Generated by Django 5.1.6 on 2025-08-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_short_description_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='big_image',
            new_name='image',
        ),
    ]
